CFLAGS = -I /scr/talkowski/tools/bin/samtools-current -L/scr/talkowski/tools/bin/samtools-current -lbam -lz

unmappedToFastq: unmappedToFastq.cpp
	g++ -o unmappedToFastq unmappedToFastq.cpp ${CFLAGS}


