#!/bin/bash
USER=`whoami`
JOBS_Q=`qselect -u $USER -s Q`
JOBS_R=`qselect -u $USER -s R`

echo "Queued jobs..."
echo $JOBS_Q

echo "Running jobs..."
echo $JOBS_R

for JOB in $JOBS_Q
do
	qdel $JOB
done

for JOB in $JOBS_R
do
	qdel $JOB
done
#qselect -u $USER -s Q | xargs qdel
#qselect -u $USER -s R | xargs qdel
